<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <DalamudApiLevel>15</DalamudApiLevel>
    <AssemblyName>OmniToolbox.Common</AssemblyName>
    <RootNamespace>OmniToolbox</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Use_DalamudPackager>false</Use_DalamudPackager>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <NuGetLockFilePath>$(BaseIntermediateOutputPath)$(MSBuildProjectName).packages.lock.json</NuGetLockFilePath>
    <NoWarn>$(NoWarn);Dalamud001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="DailyRoutines.CodeAnalysis" Version="2.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="LuminaSupplemental.Excel" Version="5.1.4" />
    <PackageReference Include="TinyPinyin" Version="1.1.0" />
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lib\KamiToolKit\KamiToolKit.csproj" />
    <ProjectReference Include="..\lib\OmenTools\OmenTools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\DATA_SOURCES.md"
                      Link="Data\DATA_SOURCES.md"
                      LogicalName="OmniToolbox.Data.DATA_SOURCES.md" />
    <EmbeddedResource Include="Data\Resources\*.*"
                      Link="Data\%(Filename)%(Extension)"
                      LogicalName="OmniToolbox.Data.%(Filename)%(Extension)" />
    <EmbeddedResource Include="Data\Resources\UI\边框.png"
                      Link="Resources\边框.png"
                      LogicalName="OmniToolbox.Resources.边框.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OmniToolbox" />
    <InternalsVisibleTo Include="OmniToolbox.TreePublic" />
    <InternalsVisibleTo Include="OmniToolbox.Tree" />
  </ItemGroup>

</Project>
